language: c
compiler:
    - clang
    - gcc

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq autoconf libtool gengetopt 
    - autoreconf --install
script: "./configure && make && ./run_test.sh"
